micronaut:
  function:
    name: com.merricklabs

slack:
  botName: quarantinebot
  token:

quarantineBot:
  quarantineDateString: 2020-03-11

logger:
  levels:
    com.merricklabs.quarantinebot: DEBUG