micronaut:
  application:
    name: quarantinebot

jackson:
  bean-introspection-module: true
  serializationInclusion: NON_NULL
  deserialization:
    failOnUnknownProperties: false

quarantineBot:
  quarantineDate: "2020-03-11"

slack:
  botName: quarantinebot
  token:

logger:
  levels:
    com.merricklabs.quarantinebot: DEBUG